name: food_share
description: Assignment project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  image_picker: ^1.0.0
  get: ^4.6.5
  firebase_storage: ^11.2.4
  firebase_core: ^2.14.0

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
     - img/
